import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import DashboardProvider from "@/contexts/actualdashboardContext";
import CircularProvider from "@/contexts/circularsContext";
import BudgetProvider from "@/contexts/budgetContext";
import LogisticsProvider from "@/contexts/logisticsContext";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <DashboardProvider>
            <CircularProvider>
              <BudgetProvider>
                <LogisticsProvider>{children}</LogisticsProvider>
              </BudgetProvider>
            </CircularProvider>
          </DashboardProvider>
        </Layout>
      </body>
    </html>
  );
}
